import './globals.css'
import { Inter } from 'next/font/google'
import CartSizeProvider from '@/contexts/cartSizeContext'
import Navbar from '@/components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CartSizeProvider>
        <Navbar />
      {children}
      </CartSizeProvider>
      </body>
    </html>
  )
}

